name: Extract
description: "Prepare to run & autograde JAR-packaged tests."
inputs:
  workspace:
    description: "Base directory of project under test."
    required: true
  consumer-actor:
    description: "Username of authenticated user for package installation"
    required: true
  consumer-token:
    description: "Personal access token of authenticated user for package installation"
    required: true
  test-destination:
    description: "Destination subdirectory of extracted test classes & configuration."
    required: false
    default: autograding
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java 
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 11
        architecture: x64
        cache: gradle
    - name: Make gradlew executable
      run: chmod +x ${{ inputs.workspace }}/gradlew
      shell: bash
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Rename existing Gradle build file
      run: mv ${{ inputs.workspace }}/build.gradle ${{ inputs.workspace }}/submitted.gradle
      shell: bash
    - name: Move autograding Gradle build files
      run: mv ${{ github.action_path }}/gradle/* ${{ inputs.workspace }}/
      shell: bash
    - name: Prepare autograding credentials
      run: ${{ inputs.workspace }}/gradlew appendProperties -build-file prepare.gradle
      shell: bash
      env:
        CONSUMER_ACTOR: ${{ inputs.consumer-actor }}
        CONSUMER_TOKEN: ${{ inputs.consumer-token }}
    - name: Extract test files
      run: ${{ inputs.workspace }}/gradlew copyConfiguration -PreportName=.
      shell: bash
